### PR TITLE
Adding Veronica's samples

### LINKED ISSUE #7: Add Veronica's samples
Please add Veronica's samples to the pack

### PR DESCRIPTION
**Pull request by vmfong**
adding new samples
this will fix #7

### CODE REVIEW

**Comment by vmfong** [comment]
this fixes #7

**Comment by vmfong** [comment]
this will fix #7

**Comment by vmfong** [comment]
this will fix #7

**Comment by vmfong** [comment]
I accidentally closed the pull request when I was trying to figure out where to add the "fix" comment.

**Comment by omarcostahamido** [comment]
No problem. I'm glad you figure it out!

**Pull request merged**
