### PR TITLE
adding Ranjith's samples

### PR DESCRIPTION
**Pull request by kumar-Ranjith**
cool samples

### CODE REVIEW

**Comment by kumar-Ranjith** [comment]
this fixes #28

**Comment by kumar-Ranjith** [comment]
add keyboard sample
this will fix #24

**Comment by omarcostahamido** [comment]
you don't want to manually close your PR. You want it to get merged with the repo, so that your changes will take effect.

**Comment by omarcostahamido** [comment]
I see, you did you again on #32 . Ok.

**Pull request closed without merging**
