### PR TITLE
Adding Lindsey's Samples final

### LINKED ISSUE #45: Adding Lindsey's samples
Please Add Lindsey's samples

### PR DESCRIPTION
**Pull request by lindsey47**
Adding Samples
this fixes #45

### CODE REVIEW

**Comment by lindsey47** [comment]
this is fixed by #46

**Comment by omarcostahamido** [comment]
please change the original message to 45.
This pull request will fix issue 45 not 46.
Then, when I merge this, it will auto close 45.

**Review by omarcostahamido — COMMENTED** [review]
PR content good now.
Just waiting for you to update that first message to 45 so that I can merge after.

**Comment by lindsey47** [comment]
> PR content good now.
> Just waiting for you to update that first message to 45 so that I can merge after.

I believe I have changed it now

**Pull request merged**
